default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV["DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: SBHShortUrl_development
  socket: /var/run/mysqld/mysqld.sock

test:
  <<: *default
  database: SBHShortUrl_test
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: <%= ENV["SBHSHORTURL_DATABASE_NAME"] %>
  username: <%= ENV["SBHSHORTURL_DATABASE_USERNAME"] %>
  password: <%= ENV["SBHSHORTURL_DATABASE_PASSWORD"] %>
  socket: /var/lib/mysql/mysql.sock
